### ISSUE TITLE
help for script/make_bu_data.py

### ISSUE THREAD

**Issue by project-zzy** [GCYZSL/CVLMN#1]
could you give me your script/make_bu_data.py?i can not found in the library.thank you very much!!

**Comment by GCYZSL** [comment]
Hi, thank you for asking! Please check it at https://github.com/ruotianluo/self-critical.pytorch/blob/master/scripts/make_bu_data.py. Feel free to ask if you have further questions!

**Comment by Wangdanchunbufuz** [comment]
> 

Thank you very much for your help！But I meet some questions during the Evaluating.Do you know the answer to this question?Thank you very much!!
![image](https://user-images.githubusercontent.com/92201550/223002841-e5700a20-ba71-4b8c-97df-dde7254544dc.png)
